### ISSUE TITLE
Debug menu harassment 

### ISSUE THREAD

**Issue by BlueColorsin** [BeastlyGhost/FNF-Feather#1]
so in summery the Debug menu text does not go away after use and it stays on screen forever 

Steps to reproduce
Press 7 in menu and go into the debug menu
go to txt converter and boom
it stays there

![NVIDIA_Share_znbZReTLMw](https://github.com/BeastlyGhost/FNF-Feather/assets/76269429/6c8c3c9c-70ff-49be-8087-890f83c14c26)

![NVIDIA_Share_e0xxh9Ef2r](https://github.com/BeastlyGhost/FNF-Feather/assets/76269429/a965e61b-ca7a-424d-9a62-6ecd20d1319f)

you can actually use it in the pause menu lmao 
![NVIDIA_Share_q29nYIuq3z](https://github.com/BeastlyGhost/FNF-Feather/assets/76269429/86a00b3b-6e58-4ace-ab7f-0c8e675d532a)

**Comment by BeastlyGhost** [comment]
I might just straight up remove the debug menu and replace it with something in the Godot editor tbh

**Comment by BeastlyGhost** [comment]
accidentally fixed in latest commit
